namespace RocketTaskPlanner.Infrastructure.Sqlite.NotificationsContext.Queries.GetNotificationReceiversByIdArray;

public record GetNotificationReceiversByIdentifiersQueryResponse(long ChatId, string ChatName);
