// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RocketTaskPlanner.Infrastructure.Sqlite.ExternalChatsManagementContext;

#nullable disable

namespace RocketTaskPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(ExternalChatsDbContext))]
    partial class ExternalChatMembersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("RocketTaskPlanner.Domain.ExternalChatsManagementContext.Entities.ExternalChat", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("OwnerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("owner_id");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("external_chats", (string)null);
                });

            modelBuilder.Entity("RocketTaskPlanner.Domain.ExternalChatsManagementContext.ExternalChatOwner", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("owners", (string)null);
                });

            modelBuilder.Entity("RocketTaskPlanner.Domain.ExternalChatsManagementContext.Entities.ExternalChat", b =>
                {
                    b.HasOne("RocketTaskPlanner.Domain.ExternalChatsManagementContext.ExternalChatOwner", "Owner")
                        .WithMany("Chats")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("RocketTaskPlanner.Domain.ExternalChatsManagementContext.ExternalChatOwner", b =>
                {
                    b.Navigation("Chats");
                });
#pragma warning restore 612, 618
        }
    }
}
