services:
  postgres:
    image: postgres
    restart: always
    container_name: rocket_db
    environment:
      POSTGRES_DB: rocket_db
      POSTGRES_USER: rocket_db_user
      POSTGRES_PASSWORD: rocket_db_password
      PGPORT: 6666
    ports:
      - "7777:6666"
    volumes:
      - bot_db_data:/var/lib/postgresql/data
  
  eshop.seq:
    image: datalust/seq:latest
    container_name: seq        
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8081:80"
      - "5341:5341"
  
  bot:
    build:
      context: .
      dockerfile: dockerfile
    container_name: telegram_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TIME_ZONE_DB_KEY=${TIME_ZONE_DB_KEY}          
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
    restart: always
    
volumes:
  bot_db_data:
  
