services:
  postgres:
    image: postgres
    restart: always
    container_name: rocket_db
    environment:
      POSTGRES_DB: rocket_db
      POSTGRES_USER: rocket_db_user
      POSTGRES_PASSWORD: rocket_db_password
      PGPORT: 6666
    ports:
      - "7777:6666"
    volumes:
      - bot_db_data:/var/lib/postgresql/data

  eshop.seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8081:80"
      - "5341:5341"

volumes:
  bot_db_data:
